apiVersion: v1
kind: Service
metadata:
    name: "keshavtest1-9115"
    labels:
        app: "keshavtest1-9115"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "keshavtest1-9115"